/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Solaris } from "./Solaris";
export * as factories from "./factories";
export { Solaris__factory } from "./factories/Solaris__factory";
